# Generated by Django 2.0.3 on 2018-11-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('street_number', models.CharField(max_length=8)),
                ('flat_number', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('m_type', models.IntegerField(choices=[(1, 'domowy'), (2, 'służbowy'), (3, 'faks'), (4, 'inny')])),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=16)),
                ('group_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.Address')),
                ('mail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.EmailAddress')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_num', models.CharField(max_length=16)),
                ('p_type', models.IntegerField(choices=[(1, 'domowy'), (2, 'służbowy'), (3, 'faks'), (4, 'inny')])),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='group',
            name='persons',
            field=models.ManyToManyField(to='addresses.Person'),
        ),
    ]
