# Generated by Django 2.0.3 on 2018-12-25 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='person',
        ),
        migrations.RemoveField(
            model_name='group',
            name='persons',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.Address'),
        ),
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='addresses.Group'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='m_type',
            field=models.IntegerField(choices=[(1, 'domowy'), (2, 'służbowy'), (3, 'faks'), (4, 'inny')], verbose_name='Rodzaj maila'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Adres email'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='p_num',
            field=models.CharField(max_length=16, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='p_type',
            field=models.IntegerField(choices=[(1, 'domowy'), (2, 'służbowy'), (3, 'faks'), (4, 'inny')], verbose_name='Rodzaj telefonu'),
        ),
    ]
