# Generated by Django 2.0.3 on 2018-12-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20181225_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=64, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.CharField(max_length=8, verbose_name='Nr mieszkania'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=64, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(max_length=8, verbose_name='Nr domu'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_desc',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=16, verbose_name='Nazwa'),
        ),
    ]
